language: c
sudo: true
before_install:
    - "echo \"deb ftp.us.debian.org/debian wheezy main\" | sudo tee /etc/apt/sources.list"
    - "sudo apt-get update"
    - "sudo apt-get install python3 lua5.2 liblua5.2-dev ia32-libs-i386"
install:
    - "git clone https://github.com/felix-lang/fbuild.git"
    - "git clone https://github.com/kirbyfan64/libcut.git"
    - "git clone https://github.com/LuaDist/luabitop.git"
    - "cd luabitop && make CFLAGS=`pkg-config --cflags lua5.2` && cd .."
script:
    - "fbuild/fbuild-light --cflag=-Ilibcut || cat build/fbuild.log && build/tst"
    - "fbuild/fbuild-light --clean"
    - "fbuild/fbuild-light --cflag=-Ilibcut --cflag=-m32 || cat build/fbuild.log && build/tst"
env:
    - "LUA_CPATH=$TRAVIS_BUILD_DIR/luabitop/?.so"
